[package]
name = "hello_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = { git = "https://github.com/fufesou/rdev" }
tfc = { git = "https://github.com/fufesou/The-Fat-Controller" }
lazy_static = "1.4"
x11 = { git="https://github.com/bjornsnoen/x11-rs", features = ["xlib"] }
anyhow = "1.0.68"
log = "0.4.17"
env_logger = "0.10.0"
nix = "0.26.1"

[[example]]
name = "server"
